tap 'bwhaley/ssmsh'
tap 'hashicorp/tap'

brew "bat"
brew "bufbuild/buf/buf"
brew "direnv"
brew "gh"
brew "jq"
brew "lsd"
brew "nano"
brew "pre-commit"
brew "ssmsh"
brew "hashicorp/tap/terraform"
brew "the_silver_searcher"
brew "yq"
brew "xz"
