tap bwhaley/ssmsh https://github.com/bwhaley/ssmsh

brew "bat"
brew "bufbuild/buf/buf"
brew "direnv"
brew "gh"
brew "jq"
brew "lsd"
brew "nano"
brew "ssmsh"
brew "the_silver_searcher"
brew "yq"
brew "xz"
