#!/bin/bash
set -e
set -o pipefail

current_branch=$(git branch --show-current)
if [[ "${current_branch}" == "dev" ]]; then
    echo "staging"
elif [[ "${current_branch}" == "staging" ]]; then
    echo "prod"
elif [[ "${current_branch}" == "prod" ]]; then
    >&2 echo "Prod has no parent"
    exit 1
else
    git show-branch 2>&1 | grep '*' | grep -v "$(git rev-parse --abbrev-ref HEAD)" | head -n1 | sed 's/.*\[\(.*\)\].*/\1/' | sed 's/[\^~].*//'
fi
